version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo
      - ./odoo-custom-addons:/mnt/extra-addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo   
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/backup_file.sql
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./main:/var/lib/postgresql/data/pgdata


volumes:
  web-data:
  odoo-db-data:
